name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.18.2
      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm docs:build
      # - name: deploy to github pages
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_PORT: 22 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          # EXCLUDE: "/dist/, /node_modules/"
