name: CI

on:
  push:
    branches:
      - master

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.18.2
      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm docs:build
      # - name: deploy to github pages
      - name: deploy to server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY  }}
          connect_timeout: 10s
          first_ssh: |
            cd ~/projects/website
            rm -rf *
          scp: |
            'dist/*' => ~/projects/website
          last_ssh: |
            echo "deploy success"
